# -*- coding: utf8 -*-
#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,slots,no_utf8strings,coding=utf8
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

